# Generated by Django 3.2.7 on 2021-09-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjimon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lugat',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Lugat '},
        ),
        migrations.AlterField(
            model_name='lugat',
            name='uzbekcha',
            field=models.CharField(max_length=128, verbose_name='O`zbekcha'),
        ),
    ]
