# Generated by Django 3.2.7 on 2021-09-11 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarjimon', '0002_auto_20210911_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lugat',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Lug`at '},
        ),
    ]
